steps:
  - id: unittest
    name: "python:3.11.6-slim-bullseye"
    script: |
      pip install poetry 
      poetry install 
      cd src/ 
      poetry run pytest
  - id: build-push-docker-image
    name: "gcr.io/cloud-builders/docker"
    script: |
      docker build --pull -t ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/$_DOCKER_REPO/ai-assistant:$COMMIT_SHA .
      docker push ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/$_DOCKER_REPO/ai-assistant:$COMMIT_SHA
  - id: deploy-infra
    name: "hashicorp/terraform"
    script: |
      cd terraform 
      terraform init 
      terraform apply --auto-approve \
        -var="image_name=${LOCATION}-docker.pkg.dev/${PROJECT_ID}/$_DOCKER_REPO/ai-assistant:$COMMIT_SHA" \
        -var="domain_name=$_DOMAIN_NAME"
substitutions:
  _DOCKER_REPO: docker-repo
  #_DOMAIN_NAME: ai-assistant.dkletran.com
options:
  env:
    - "COMMIT_SHA=$COMMIT_SHA"
    - "LOCATION=$LOCATION"
    - "PROJECT_ID=$PROJECT_ID"
    - "_DOCKER_REPO=$_DOCKER_REPO"
    - "_DOMAIN_NAME=$_DOMAIN_NAME"
