steps:
  - id: unittest
    name: "python:3.11.6-slim-bullseye"
    script: |
      pip install poetry 
      poetry install 
      cd src/ 
      poetry run pytest
  - id: build-push-docker-image
    name: "gcr.io/cloud-builders/docker"
    script: |
      docker build --pull -t europe-west1-docker.pkg.dev/ai-assistant-399819/docker-repo/ai-assistant:$COMMIT_SHA .
      docker push europe-west1-docker.pkg.dev/ai-assistant-399819/docker-repo/ai-assistant:$COMMIT_SHA
  - id: deploy-infra
    name: "hashicorp/terraform"
    script: |
      cd terraform 
      terraform init 
      terraform apply --auto-approve -var="image_tag=$COMMIT_SHA"
options:
  env:
    - "COMMIT_SHA=$COMMIT_SHA"
